# Generated by Django 5.2.3 on 2025-06-30 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The memory content')),
                ('title', models.CharField(blank=True, help_text='Optional title for the memory', max_length=255, null=True)),
                ('memory_type', models.CharField(choices=[('personal', 'Personal Information'), ('preference', 'User Preference'), ('goal', 'Goal or Objective'), ('insight', 'Insight or Learning'), ('fact', 'Important Fact'), ('context', 'Contextual Information')], default='personal', max_length=20)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding of the memory content', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing memories')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importance_score', models.FloatField(default=0.5, help_text='Importance score (0.0 to 1.0)')),
                ('last_accessed', models.DateTimeField(auto_now_add=True, help_text='When this memory was last accessed')),
                ('access_count', models.IntegerField(default=0, help_text='How many times this memory has been accessed')),
                ('is_auto_extracted', models.BooleanField(default=False, help_text='Was this memory automatically extracted')),
                ('extraction_confidence', models.FloatField(blank=True, help_text='Confidence score for auto-extraction', null=True)),
                ('source_conversation', models.ForeignKey(blank=True, help_text='Conversation this memory was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.conversation')),
                ('source_message', models.ForeignKey(blank=True, help_text='Original message this memory was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-updated_at', '-importance_score'],
            },
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
    ]
