# Generated by Django 5.2.3 on 2025-06-30 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_memory_delete_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-importance', '-updated_at']},
        ),
        migrations.RemoveField(
            model_name='memory',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='extraction_confidence',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='importance_score',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_auto_extracted',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='memory_type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='source_conversation',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='source_message',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='title',
        ),
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.conversation'),
        ),
        migrations.AddField(
            model_name='memory',
            name='importance',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'category'], name='api_memory_user_id_676676_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'importance'], name='api_memory_user_id_b0bb83_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'is_active'], name='api_memory_user_id_c57822_idx'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
