# Generated by Django 5.2.3 on 2025-06-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usernote_alter_memory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-importance_score', '-updated_at']},
        ),
        migrations.AddField(
            model_name='memory',
            name='access_count',
            field=models.IntegerField(default=0, help_text='Number of times this memory has been accessed'),
        ),
        migrations.AddField(
            model_name='memory',
            name='embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vector embedding for similarity search'),
        ),
        migrations.AddField(
            model_name='memory',
            name='extraction_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence of memory extraction (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='memory',
            name='importance_score',
            field=models.FloatField(default=0.5, help_text='Numerical importance score (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_auto_extracted',
            field=models.BooleanField(default=True, help_text='Whether this memory was automatically extracted'),
        ),
        migrations.AddField(
            model_name='memory',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time this memory was used in RAG', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('preference', 'Preference'), ('goal', 'Goal'), ('personal', 'Personal'), ('professional', 'Professional'), ('relationship', 'Relationship'), ('challenge', 'Challenge'), ('skill', 'Skill'), ('interest', 'Interest'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='memory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memory',
            name='source_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_memories', to='api.conversation'),
        ),
        migrations.AddField(
            model_name='memory',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.message'),
        ),
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'memory_type'], name='api_memory_user_id_fcfdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'importance_score'], name='api_memory_user_id_b5cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'access_count'], name='api_memory_user_id_0d95be_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'last_accessed'], name='api_memory_user_id_7134a1_idx'),
        ),
    ]
