# Generated by Django 5.2.3 on 2025-06-30 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_memory_options_memory_access_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-updated_at', '-importance_score'], 'verbose_name_plural': 'Memories'},
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_676676_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_b0bb83_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_c57822_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_fcfdd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_b5cdcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_0d95be_idx',
        ),
        migrations.RemoveIndex(
            model_name='memory',
            name='api_memory_user_id_7134a1_idx',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='context',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='memory',
            name='access_count',
            field=models.IntegerField(default=0, help_text='How many times this memory has been accessed'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='content',
            field=models.TextField(help_text='The memory content'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding of the memory content', null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='extraction_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for auto-extraction', null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='importance_score',
            field=models.FloatField(default=0.5, help_text='Importance score (0.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='is_auto_extracted',
            field=models.BooleanField(default=False, help_text='Was this memory automatically extracted'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this memory was last accessed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('personal', 'Personal Information'), ('preference', 'User Preference'), ('goal', 'Goal or Objective'), ('insight', 'Insight or Learning'), ('fact', 'Important Fact'), ('context', 'Contextual Information')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='memory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='source_conversation',
            field=models.ForeignKey(blank=True, help_text='Conversation this memory was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.conversation'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='source_message',
            field=models.ForeignKey(blank=True, help_text='Original message this memory was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='api.message'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorizing memories'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the memory', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
    ]
