# Generated by Django 5.2.3 on 2025-06-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usernote_user_alter_memory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_prompt', models.TextField(help_text='Complete prompt sent to LLM')),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt portion')),
                ('memory_context', models.TextField(blank=True, help_text='Memory context included')),
                ('conversation_history', models.TextField(blank=True, help_text='Conversation history included')),
                ('model_used', models.CharField(default='gpt-4.1-nano', max_length=50)),
                ('mode_used', models.CharField(default='conversational', max_length=20)),
                ('temperature', models.FloatField(default=0.0)),
                ('prompt_length', models.IntegerField(default=0, help_text='Length of full prompt in characters')),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='Token count of prompt', null=True)),
                ('response_tokens', models.IntegerField(blank=True, help_text='Token count of response', null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Total tokens used', null=True)),
                ('memories_used_count', models.IntegerField(default=0, help_text='Number of memories included')),
                ('relevant_memories_count', models.IntegerField(default=0, help_text='Number of relevant memories')),
                ('conversation_memories_count', models.IntegerField(default=0, help_text='Number of conversation memories')),
                ('history_messages_count', models.IntegerField(default=0, help_text='Number of history messages included')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('api_error', models.TextField(blank=True, help_text='Any API error that occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_response', models.ForeignKey(blank=True, help_text='The bot response generated from this prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_debug_response', to='api.message')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debugs', to='api.conversation')),
                ('user_message', models.ForeignKey(help_text='The user message that triggered this prompt', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debug', to='api.message')),
            ],
            options={
                'verbose_name': 'Prompt Debug Entry',
                'verbose_name_plural': 'Prompt Debug Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
