# Generated by Django 5.2.3 on 2025-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_promptdebug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'memory_type'], name='api_memory_user_id_fcfdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'importance_score'], name='api_memory_user_id_b5cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'is_auto_extracted'], name='api_memory_user_id_17caa0_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'access_count'], name='api_memory_user_id_0d95be_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'last_accessed'], name='api_memory_user_id_7134a1_idx'),
        ),
    ]
