# Generated by Django 5.2.3 on 2025-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memory_api_memory_user_id_fcfdd6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_prompt',
            field=models.TextField(blank=True, help_text='Complete prompt sent to LLM (for debugging)'),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_user_input',
            field=models.TextField(blank=True, help_text='Original user input before prompt construction'),
        ),
    ]
