# Generated by Django 5.2.3 on 2025-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the memory was last edited by the user.', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the memory was last accessed.', null=True),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', '-created_at'], name='api_memory_user_id_318153_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', '-last_accessed_at'], name='api_memory_user_id_1f6f0a_idx'),
        ),
    ]
