# Generated by Django 5.2.3 on 2025-08-29 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_memory_edited_at_memory_last_accessed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('calendar', 'Calendar'), ('drive', 'Google Drive')], max_length=50)),
                ('name', models.CharField(help_text='User-friendly name for the connector', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Authentication')], default='pending', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_uri', models.URLField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list, help_text='OAuth scopes required')),
                ('config', models.JSONField(default=dict, help_text='Connector-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_authenticated', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'connector_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MCPOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('send_email', 'Send Email'), ('read_email', 'Read Email'), ('search_emails', 'Search Emails'), ('list_labels', 'List Labels'), ('create_label', 'Create Label'), ('modify_email', 'Modify Email'), ('delete_email', 'Delete Email')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('request_data', models.JSONField(default=dict, help_text='Request parameters')),
                ('response_data', models.JSONField(default=dict, help_text='Response data')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.mcpconnector')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
