# Generated by Django 5.2.3 on 2025-08-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mcpconnector_mcpoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpconnector',
            name='credentials_data',
            field=models.JSONField(blank=True, help_text='OAuth credential payload', null=True),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='has_refresh_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcpconnector',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='Access token expiry', null=True),
        ),
    ]
